//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ucCodeEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ucCodeEditor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DUT操作函数模块
        ///
        ///local modname=...;
        ///local M={};
        ///_G[modname]=M;
        ///package.loaded[modname]=M;
        ///
        ///--Marco define
        ///--instance is fixture
        ///local DUT_LOG = 1;	--记录调试信息
        ///local function DUT_log(fmt,...)
        ///	if (DUT_LOG ~=0) then
        ///		--Log(&quot;	:)&quot;..string.format(fmt,...),ID);
        ///        Log(&quot;	:)&quot;..tostring(fmt),ID);
        ///	end
        ///end
        ///
        ///
        ///function M.GetOhmData(Index)
        ///	return A2750A:GetOhmData(Index);
        ///end
        ///
        ///
        ///function M.OpenDevice()
        ///	return A2750A:OpenDevice();
        ///end
        ///
        ///function M.storyOhmData(Chanel,ResType,count)
        ///	return A275 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LuaSource {
            get {
                return ResourceManager.GetString("LuaSource", resourceCulture);
            }
        }
    }
}
